[tool.poetry]
name = "mrtools"
version = "0.1.0"
description = "Modern ROOT Tools for CMS Physics Analysis at HEPHY"
authors = ["Dietrich Liko <Dietrich.Liko@oeaw.ac.at>"]

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.2"
SQLAlchemy = "^1.3.24"
jsonschema = "^4.4.0"
datasize = "^1.0.0"
tomli = "^2.0.1"
"ruamel.yaml" = "^0.17.21"
dask = "^2022.5.0"
distributed = "^2022.5.0"
dask-jobqueue = "^0.7.3"

[tool.poetry.dev-dependencies]
pytest = "^7.1.0"
black = "^22.3.0"
flake8 = "^4.0.1"
flake8-bugbear = "^22.1.11"
flake8-docstrings = "^1.6.0"
mypy = "^0.931"
reorder-python-imports = "^2.7.1"

[tool.poetry.scripts]
example01 = "examples.example01:main"
ex01_plot01 = "examples.ex01_plot01:main"
check_weights = "examples.check_weights:main"
plot01 = "examples.plot01:main"
printtree = "examples.printtree:main"
make_nanoNtuple = "examples.make_nanoNtuple:main"
thstack = "examples.thstack:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
