# 
[samples_cache]
# xrdcp_retry = 3
# threads = 4

[site.vienna]
domains = [ "cbe.vbc.ac.at" ]

store_path = "/eos/vbc/experiments/cms"
local_url = "root://eos.grid.vbc.ac.at/"
global_url = "root://eos.grid.vbc.ac.at/"

stage = true
stage_path = "/scratch-cbe/users/$USER/cache"

batch = "SLURM"

[site.cern]
domains = [ "cern.ch" ]

store_path = "/eos/vbc/experiments/cms"
local_url = "root://eoscms.cern.ch/"
global_url = "root://eos.grid.vbc.ac.at/"

stage = false

batch = "HTCondor"

[binaries]
# dasgoclient = 
# voms-proxy-init =
# voms-proxy-info =
